#####################
# model config    #
#####################
model: Qwen/Qwen2-0.5B
cache_dir: /data1/hy/models

image_size: [384, 384]
patch_size: [16, 16]
num_channels: 3
hidden_size: 896


#####################
# data config     #
#####################
lang_dir: assets/font
background_img_dir: assets/background
db_dir: assets/debug_dict
max_length: 160
max_sentence_length: 30



#####################
# training config  #
#####################
train_samples: 10
eval_samples: 2